version: "3"

services:
  fiber-pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - fiber-pg-data:/var/lib/postgres

    networks:
      - authf-network

  fiber-redis:
    image: redis:latest

    volumes:
      - fiber-redis-data:/data

    networks:
      - authf-network
networks:
  authf-network:
    driver: bridge
volumes:
  fiber-pg-data:
  fiber-redis-data:
